spring:
  datasource:
    initialization-mode: always
    schema: schema.sql
    data: data.sql
  messages:
    basename: i18n.messages
    fallback-to-system-locale: false
  shell:
    interactive:
      enabled: true
application:
  default-locale-tag: ru-RU